[book]
authors = ["The Optimism Collective"]
language = "en"
multilingual = false
src = "src"
title = "Optimism PM Docs"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/ethereum-optimism/pm/"
